#include <stdlib.h>
#include <stdio.h>
#include <assert.h>

#include "sitenode.h"
#include "parameter.h"

int main() {

	printf("This test script is designed to only test the functions\n");
  printf("within sitenode.c. It is designed examine all the inpu-\n");
  printf("ts and ensure correct output. If this script is run su-\n");
	printf("ccessfully without crashing no errors were found in the\n");
  printf("library\n");

	int i, j, k;
	//Do not change these values
	int len=3, wid=4, hei=3;
	int rv;
	double rvd;
	void * rvpt;

	printf("\nTesting Site node code\n");	
	
	printf("\nTesting:newPoint Creating point\n");
	Point pt = newPoint();
	assert(pt!=NULL);
	printf("Testing:printPoint Printing point\n");
	rv = printPoint(NULL);
	assert(rv==-1);
	rv = printPoint((void*) pt);
	assert(rv==0);
	printf("Testing:getsumPt grabbing sum value of new point\n");
	rvd = getsumPt(pt);
	printf("\nTesting:deletePoint Deleting point\n");
	rv = deletePoint(NULL);
	assert(rv==-1);
	rv = deletePoint(pt);
	assert(rv==0);

	Point ptr = newPoint();
	Point ptr2;
	
	printf("Testing:newSN Created Site node\n");
	SiteNode sn = newSN();
	assert(sn!=NULL);
	printf("Testing:getPoint grabbing the Datastructure of a new sitenode\n");
	rvpt = getPoint(sn);
	assert(rvpt!=NULL);
	printf("Testing:getCluster grabbing the Neighlist of new sitenode\n");
	rvpt = getClusterList(sn);
	assert(rvpt==NULL);
	printf("Testing:getDwelStat grabbing dwell status of new sitenode\n");
	rv = getDwelStat(sn);
	assert(rv==-1);
	printf("Testing:setDwelStat\n");
	rv = setDwelStat(NULL,2);
	assert(rv==-1);
	rv = getDwelStat(sn);
	assert(rv==-1);
	rv = setDwelStat(sn,-2);
	assert(rv==-1);
	rv = getDwelStat(sn);
	assert(rv==-1);
	rv = setDwelStat(sn,4);
	assert(rv==0);
	rv=getDwelStat(sn);
	assert(rv==4);
	printf("Testing:getVisFreq grabbing visitation frequency of new sitenode\n");
	rvd = getVisFreq(sn);
	assert(rvd==0);
	printf("Testing:setVisFreq\n");
	rv = setVisFreq(NULL,2);
	assert(rv==-1);
	rv = setVisFreq(sn,-1);
	assert(rv==-1);
	rv = setVisFreq(sn,9);
	assert(rv==0);
	rvd = getVisFreq(sn);
	assert(rvd==9);
	printf("Testing:incVisFreq\n");
	incVisFreq(sn);
	rvd = getVisFreq(sn);
	assert(rvd==10);
	printf("Testing:getVis grabbing visitation of new sitenode\n");
	rvd = getVis(sn);
	assert(rvd==0);
	printf("Testing:setVis\n");
	rv = setVis(sn,-2);
	assert(rv==-1);
	rv = setVis(NULL,1);
	assert(rv==-1);
	rv = setVis(sn,1);
	assert(rv==0);
	rvd=getVis(sn);
	assert(rv=1.0);

	printf("Testing:setInitE\n");
	rv = setInitE(NULL,1);
	assert(rv==-1);
	rv = setInitE(sn,-1);
	assert(rv==-1);
	rv = setInitE(sn,2);
	assert(rv==-1);
	rv = setInitE(sn,1);
	assert(rv==0);

	printf("Testing:getInitE grabbing initE parameter of new sitenode\n");
	rv = getInitE(NULL);
	assert(rv==-1);
	rv = getInitE(sn);
	assert(rv==1);
	printf("Testing:setEnergy\n");
	rv = setEnergy(NULL,2.2);
	assert(rv==-1);
	rv = setEnergy(sn,-9.3);
	assert(rv==0);
	printf("Testing:getEnergy grabbing energy of new sitenode\n");
	rvd = getEnergy(sn);
	assert(rvd==-9.3);
	printf("Testing:getType grabbing type from new sitenode\n");
	rv = getType(NULL);
	assert(rv==-1);
	rv = getType(sn);
	assert(rv==0);
	printf("Testing:setDataStruc\n");
	rv = setDataStruc(NULL,0,(void*) ptr);
	assert(rv==-1);
	rv = setDataStruc(sn,-1,(void*)ptr);
	assert(rv==-1);
	rv = setDataStruc(sn,2,(void*)ptr);
	assert(rv==-1);
	rv = setDataStruc(sn,0,NULL);
	assert(rv==-1);
	ptr2 = (Point) getPoint(sn);
	rv = setDataStruc(sn,0,(void*)ptr);
	assert(rv==0);
	rv = getType(sn);
	assert(rv==0);
	rvpt = getClusterList(sn);
	assert(rvpt==NULL);
	rv = setDataStruc(sn,1,(void*)ptr);
	assert(rv==0);
	rv = getType(sn);
	assert(rv==1);
	printf("Testing:setDataStruc\n");
	rv = setDataStruc(NULL,0,(void*)ptr2);
	assert(rv==-1);
	rv = setDataStruc(sn,0,NULL);
	assert(rv==-1);
	rv = setDataStruc(sn,0,(void*)ptr2);
	assert(rv==0);
	ptr2 = (Point) getClusterList(sn);
	assert(ptr2!=NULL);
	printf("Testing:setDataStruc\n");
	rv = setDataStruc(sn,0,(void*)ptr);
	assert(rv==0);
	ptr2 = (Point) getPoint(sn);
	assert(ptr2!=NULL);
	rv = setDataStruc(sn,0,(void*)ptr);
	assert(rv==0);
	rvpt = getClusterList(sn);
	assert(rvpt!=NULL);

	printf("Testing:deleteSN Deleting Site node\n");
	rv = deleteSN(NULL);
	assert(rv==-1);
	rv = deleteSN(sn);
	assert(rv==0);

	printf("\nTesting:newSNarray Creating Site node array\n");
	SNarray snA=newSNarray(-1,wid,hei);
	assert(snA==NULL);
	snA=newSNarray(len,-1,hei);
	assert(snA==NULL);
	snA=newSNarray(len,wid,-4);
	assert(snA==NULL);
	snA=newSNarray(len,wid,hei);
	assert(snA!=NULL);
	printf("Testing:getIndex Locating the index of individual sites within snA\n");
	rv = getIndex(NULL,0,1,2);
	assert(rv==-1);
	rv = getIndex(snA,-2,1,0);
	assert(rv==-1);
	rv = getIndex(snA,2,-1,1);
	assert(rv==-1);
	rv = getIndex(snA,3,1,2);
	assert(rv==-1);
	rv = getIndex(snA,1,1,1);
	assert(rv==16);
	rv = getIndex(snA,0,0,0);
	assert(rv==0);
	rv = getIndex(snA,2,3,2);
	assert(rv==(3*4*3-1));
	printf("Testing:getLoc Grabbing the location from snA\n");
	rv = getLoc( &i, &j, &k, 5, NULL);
	assert(rv==-1);
	rv = getLoc( &i, &j, &k, 36, snA);
	assert(rv==-1);
	rv = getLoc( &i, &j, &k, -2, snA);
	assert(rv==-1);
	rv = getLoc( &i, &j, &k, 35, snA);
	assert(rv==0);
	assert(i==2);
	assert(j==3);
	assert(k==2);
	rv = getLoc( &i, &j, &k, 0, snA);
	assert(rv==0);
	assert(i==0);
	assert(j==0);
	assert(k==0);
	rv = getIndex( snA,1, 3,1);
	assert(rv==22);
	rv = getLoc( &i, &j, &k, rv, snA);
	printf("i %d j %d k %d\n",i,j,k);
	assert(i==1);
	assert(j==3);
	assert(k==1);
	printf("Testing:getSN Getting Site Node from snA\n");
	SiteNode sn1 = getSN(snA,1,1,1);
	assert(sn1!=NULL);
	sn1 = getSN(snA,32,30,500);
	assert(sn1==NULL);
	sn1 = getSN(snA,-2,2,1);
	assert(sn1==NULL);
	sn1 = getSN(snA, 1,-1,2);
	assert(sn1==NULL);
	sn1 = getSN(snA, 1,3,-2);
	assert(sn1==NULL);
	sn1 = getSN(snA,0,0,0);
	assert(sn1!=NULL);

	printf("Testing:getIndexFront\n");
	rv = getIndexFront(snA,getIndex(snA,2,3,2));
	assert(rv==-1);
	rv = getIndexFront(snA,getIndex(snA,1,3,2));
	assert(rv==35);
	rv = getIndexFront(snA,-1);
	assert(rv==-1);
	rv = getIndexFront(snA,36);
	assert(rv==-1);
	printf("Testing:getIndexBehind\n");
	rv = getIndexBehind(snA,getIndex(snA,0,2,2));
	assert(rv==-1);
	rv = getIndexBehind(snA,getIndex(snA,1,2,2));
	assert(rv==8);
	rv = getIndexBehind(snA,-1);
	assert(rv==-1);
	rv = getIndexBehind(snA,36);
	assert(rv==-1);
	printf("Testing:getIndexLeft\n");
	rv = getIndexLeft(snA,getIndex(snA,2,0,2));
	assert(rv==-1);
	rv = getIndexLeft(snA,getIndex(snA,1,2,2));
	assert(rv==17);
	rv = getIndexLeft(snA,-1);
	assert(rv==-1);
	rv = getIndexLeft(snA,36);
	assert(rv==-1);
	printf("Testing:getIndexRight\n");
	rv = getIndexRight(snA,getIndex(snA,0,3,2));
	assert(rv==-1);
	rv = getIndexRight(snA,getIndex(snA,1,2,2));
	assert(rv==23);
	rv = getIndexRight(snA,-1);
	assert(rv==-1);
	rv = getIndexRight(snA,36);
	assert(rv==-1);
	printf("Testing:getIndexBelow\n");
	rv = getIndexBelow(snA,getIndex(snA,0,2,0));
	assert(rv==-1);
	rv = getIndexBelow(snA,getIndex(snA,1,2,2));
	assert(rv==19);
	rv = getIndexBelow(snA,-1);
	assert(rv==-1);
	rv = getIndexBelow(snA,36);
	assert(rv==-1);
	printf("Testing:getIndexAbove\n");
	rv = getIndexAbove(snA,getIndex(snA,0,2,2));
	assert(rv==-1);
	rv = getIndexAbove(snA,getIndex(snA,1,2,1));
	assert(rv==20);
	rv = getIndexAbove(snA,-1);
	assert(rv==-1);
	rv = getIndexAbove(snA,36);
	assert(rv==-1);
	
	printf("Testing:getIndexLeftPeriodic\n");
	rv = getIndexLeftPeriodic(snA,getIndex(snA,1,0,2));
	assert(rv==23);
	rv = getIndexLeftPeriodic(snA,getIndex(snA,1,2,1));
	assert(rv==16);
	rv = getIndexLeftPeriodic(snA,-1);
	assert(rv==-1);
	rv = getIndexLeftPeriodic(snA,36);
	assert(rv==-1);
	printf("Testing:getIndexRightPeriodic\n");
	rv = getIndexRightPeriodic(snA,getIndex(snA,1,3,2));
	assert(rv==14);
	rv = getIndexRightPeriodic(snA,getIndex(snA,1,2,0));
	assert(rv==21);
	rv = getIndexRightPeriodic(snA,-1);
	assert(rv==-1);
	rv = getIndexRightPeriodic(snA,36);
	assert(rv==-1);
	printf("Testing:getIndexPeriodicY\n");
	rv = getIndexPeriodicY(NULL,1,1,1);
	assert(rv==-1);
	rv = getIndexPeriodicY(snA,0,0,0);
	assert(rv==0);
	rv = getIndexPeriodicY(snA,2,3,2);
	assert(rv==35);
	rv = getIndexPeriodicY(snA,-1,2,1);
	assert(rv==-1);
	rv = getIndexPeriodicY(snA,0,-1,1);
	assert(rv==10);
	rv = getIndexPeriodicY(snA,0,0,-1);
	assert(rv==-1);
	rv = getIndexPeriodicY(snA,3,0,1);
	assert(rv==-1);
	rv = getIndexPeriodicY(snA,2,4,1);
	assert(rv==25);
	rv = getIndexPeriodicY(snA,2,0,3);
	assert(rv==-1);
	printf("Testing:getIndexPeriodicZ\n");
	rv = getIndexPeriodicZ(NULL,1,1,1);
	assert(rv==-1);
	rv = getIndexPeriodicZ(snA,0,0,0);
	assert(rv==0);
	rv = getIndexPeriodicZ(snA,2,3,2);
	assert(rv==35);
	rv = getIndexPeriodicZ(snA,-1,1,1);
	assert(rv==-1);
	rv = getIndexPeriodicZ(snA,1,-1,1);
	assert(rv==-1);
	rv = getIndexPeriodicZ(snA,0,1,-1);
	assert(rv==5);
	rv = getIndexPeriodicZ(snA,3,1,1);
	assert(rv==-1);
	rv = getIndexPeriodicZ(snA,1,4,1);
	assert(rv==-1);
	rv = getIndexPeriodicZ(snA,0,1,3);
	assert(rv==3);
	printf("Testing:getIndexPeriodic\n");
	rv = getIndexPeriodic(NULL,1,1,1);
	assert(rv==-1);
	rv = getIndexPeriodic(snA,0,0,0);
	assert(rv==0);
	rv = getIndexPeriodic(snA,2,3,2);
	assert(rv==35);
	rv = getIndexPeriodic(snA,-1,1,1);
	assert(rv==28);
	rv = getIndexPeriodic(snA,3,1,1);
	assert(rv==4);
	rv = getIndexPeriodic(snA,0,-1,1);
	assert(rv==10);
	rv = getIndexPeriodic(snA,0,4,1);
	assert(rv==1);
	rv = getIndexPeriodic(snA,0,0,-1);
	assert(rv==2);
	rv = getIndexPeriodic(snA,0,0,3);
	assert(rv==0);

	printf("Testing:getIndFro\n");
	rv = getIndFro( snA, 0, 0, 0);
	assert(rv==12);
	rv = getIndFro( snA, -1, 0, 0);
	assert(rv==-1);
	rv = getIndFro( snA, 2, 0, 0);
	assert(rv==-1);
	rv = getIndFro( snA, 1,-2, 0);
	assert(rv==-1);
	rv = getIndFro( snA, 1, 1, -1);
	assert(rv==-1);
	rv = getIndFro( snA, 1, 4, 0);
	assert(rv==-1);
	rv = getIndFro(snA, 1, 0, 3);
	assert(rv==-1);
	printf("Testing:getIndBeh\n");
	rv = getIndBeh( snA, 0, 0, 0);
	assert(rv==-1);
	rv = getIndBeh( snA, 3, 0, 0);
	assert(rv==-1);
	rv = getIndBeh( snA, 2, 0, 0);
	assert(rv==12);
	rv = getIndBeh( snA, 1,-2, 0);
	assert(rv==-1);
	rv = getIndBeh( snA, 1, 1, -1);
	assert(rv==-1);
	rv = getIndBeh( snA, 1, 4, 0);
	assert(rv==-1);
	rv = getIndBeh(snA, 1, 0, 3);
	assert(rv==-1);
	printf("Testing:getIndLef\n");
	rv = getIndLef( snA, 0, 0, 0);
	assert(rv==-1);
	rv = getIndLef( snA, 0, 4, 0);
	assert(rv==-1);
	rv = getIndLef( snA, 3, 1, 0);
	assert(rv==-1);
	rv = getIndLef( snA, -1, 1, 0);
	assert(rv==-1);
	rv = getIndLef( snA, 0, 1, -1);
	assert(rv==-1);
	rv = getIndLef( snA, 0, 1, 3);
	assert(rv==-1);
	rv = getIndLef(snA, 0, 1, 0);
	assert(rv==0);
	printf("Testing:getIndRig\n");
	rv = getIndRig( snA, 0, -1, 0);
	assert(rv==-1);
	rv = getIndRig( snA, 0, 3, 0);
	assert(rv==-1);
	rv = getIndRig( snA, 3, 1, 0);
	assert(rv==-1);
	rv = getIndRig( snA, -1, 1, 0);
	assert(rv==-1);
	rv = getIndRig( snA, 0, 1, -1);
	assert(rv==-1);
	rv = getIndRig( snA, 0, 1, 3);
	assert(rv==-1);
	rv = getIndRig(snA, 0, 1, 0);
	assert(rv==6);
	printf("Testing:getIndAbo\n");
	rv = getIndAbo( snA, 0, 0, -1);
	assert(rv==-1);
	rv = getIndAbo( snA, 0, 0, 2);
	assert(rv==-1);
	rv = getIndAbo( snA, 3, 0, 1);
	assert(rv==-1);
	rv = getIndAbo( snA, -1, 0, 1);
	assert(rv==-1);
	rv = getIndAbo( snA, 0, -1, 1);
	assert(rv==-1);
	rv = getIndAbo( snA, 0, 4, 1);
	assert(rv==-1);
	rv = getIndAbo(snA, 0, 0, 1);
	assert(rv==2);
	printf("Testing:getIndBel\n");
	rv = getIndBel( snA, 0, 0, 0);
	assert(rv==-1);
	rv = getIndBel( snA, 0, 0, 3);
	assert(rv==-1);
	rv = getIndBel( snA, 3, 0, 1);
	assert(rv==-1);
	rv = getIndBel( snA, -1, 0, 1);
	assert(rv==-1);
	rv = getIndBel( snA, 0, -1, 1);
	assert(rv==-1);
	rv = getIndBel( snA, 0, 4, 1);
	assert(rv==-1);
	rv = getIndBel(snA, 0, 0, 1);
	assert(rv==0);

	printf("Testing:getIndLefP\n");
	rv = getIndLefP( snA, 0, 0 ,0);
	assert(rv == 9);
	rv = getIndLefP( snA, 0, 4 , 0);
	assert(rv == -1);
	rv = getIndLefP( snA, 3, 1, 0);
	assert(rv==-1);
	rv = getIndLefP( snA, -1, 1, 0);
	assert(rv==-1);
	rv = getIndLefP( snA, 0, 1, -1);
	assert(rv==-1);
	rv = getIndLefP( snA, 0, 1, 3);
	assert(rv==-1);
	rv = getIndLefP( snA, 0, 1 ,0);
	assert(rv == 0);
	printf("Testing:getIndRigP\n");
	rv = getIndRigP( snA, 0, 0 ,0);
	assert(rv == 3);
	rv = getIndRigP( snA, 0, -1 , 0);
	assert(rv == -1);
	rv = getIndRigP( snA, 3, 1, 0);
	assert(rv==-1);
	rv = getIndRigP( snA, -1, 1, 0);
	assert(rv==-1);
	rv = getIndRigP( snA, 0, 1, -1);
	assert(rv==-1);
	rv = getIndRigP( snA, 0, 1, 3);
	assert(rv==-1);
	rv = getIndRigP( snA, 0, 3 ,0);
	assert(rv == 0);
	printf("Testing:getIndBelP\n");
	rv = getIndBelP( snA, 0, 0 ,0);
	assert(rv == 2);
	rv = getIndBelP( snA, 0, 1 , 3);
	assert(rv == -1);
	rv = getIndBelP( snA, 3, 0, 1);
	assert(rv==-1);
	rv = getIndBelP( snA, -1, 0, 1);
	assert(rv==-1);
	rv = getIndBelP( snA, 0, -1, 1);
	assert(rv==-1);
	rv = getIndBelP( snA, 0, 4, 1);
	assert(rv==-1);
	rv = getIndBelP( snA, 0, 0 ,1);
	assert(rv == 0);
	printf("Testing:getIndAboP\n");
	rv = getIndAboP( snA, 0, 0 ,0);
	assert(rv == 1);
	rv = getIndAboP( snA, 0, 1 , -1);
	assert(rv == -1);
	rv = getIndAboP( snA, 3, 0, 1);
	assert(rv==-1);
	rv = getIndAboP( snA, -1, 0, 1);
	assert(rv==-1);
	rv = getIndAboP( snA, 0, -1, 1);
	assert(rv==-1);
	rv = getIndAboP( snA, 0, 4, 1);
	assert(rv==-1);
	rv = getIndAboP( snA, 0, 0 ,2);
	assert(rv == 0);

	printf("Testing:getAlen\n");
	rv = getAlen(NULL);
	assert(rv==-1);
	rv = getAlen(snA);
	assert(rv==3);
	printf("Testing:getAwid\n");
	rv = getAwid(NULL);
	assert(rv==-1);
	rv = getAwid(snA);
	assert(rv==4);
	printf("Testing:getAhei\n");
	rv = getAhei(NULL);
	assert(rv==-1);
	rv = getAhei(snA);
	assert(rv==3);
	printf("Testing:getAtotal\n");
	rv = getAtotal(NULL);
	assert(rv==-1);
	rv = getAtotal(snA);
	assert(rv==36);

	printf("Testing:setDwelStat\n");
	sn1 = getSN(snA,1,1,1);
	setDwelStat(sn1,32);
	rv = getDwelStat(sn1);
	assert(rv==32);


	printf("Testing:getUnOccYZplane\n");
	rv = getUnOccYZplane(snA,0);
	assert(rv == 12);
	rv = getUnOccYZplane(NULL,0);
	assert(rv==-1);
	rv = getUnOccYZplane(snA,-1);
	assert(rv==-1);
	rv = getUnOccYZplane(snA,3);
	assert(rv==-1);
	rv = getUnOccYZplane(snA,1);
	assert(rv==11);
	rv = getUnOccYZplane(snA,2);
	assert(rv==12);

	printf("Testing:OccXpos\n");
	rv = OccXpos( NULL, 1, 1,1);
	assert(rv==-1);
	rv = OccXpos( snA, 1, 1,1);
	assert(rv==0);
	rv = OccXpos( snA, 2, 1,1);
	assert(rv==-1);
	rv = OccXpos( snA, -1, 1,1);
	assert(rv==-1);
	rv = OccXpos( snA, 1, -1,1);
	assert(rv==-1);
	rv = OccXpos( snA, 1, 4,1);
	assert(rv==-1);
	rv = OccXpos( snA, 1, 1,-1);
	assert(rv==-1);
	rv = OccXpos( snA, 1, 1,3);
	assert(rv==-1);
	rv = OccXpos( snA, 0, 1, 1);
	assert(rv==1);
	printf("Testing:OccXneg\n");
	rv = OccXneg( NULL, 1, 1,1);
	assert(rv==-1);
	rv = OccXneg( snA, 1, 1,1);
	assert(rv==0);
	rv = OccXneg( snA, 0, 1,1);
	assert(rv==-1);
	rv = OccXneg( snA, 3, 1,1);
	assert(rv==-1);
	rv = OccXneg( snA, 1, -1,1);
	assert(rv==-1);
	rv = OccXneg( snA, 1, 4,1);
	assert(rv==-1);
	rv = OccXneg( snA, 1, 1,-1);
	assert(rv==-1);
	rv = OccXneg( snA, 1, 1,3);
	assert(rv==-1);
	rv = OccXneg( snA, 2, 1, 1);
	assert(rv==1);
	printf("Testing:OccYpos\n");
	rv = OccYpos( NULL, 1, 1,1);
	assert(rv==-1);
	rv = OccYpos( snA, 1, 1,1);
	assert(rv==0);
	rv = OccYpos( snA, 1, 3,1);
	assert(rv==-1);
	rv = OccYpos( snA, 1, -1,1);
	assert(rv==-1);
	rv = OccYpos( snA, -1, 1,1);
	assert(rv==-1);
	rv = OccYpos( snA, 3, 1,1);
	assert(rv==-1);
	rv = OccYpos( snA, 1, 1,-1);
	assert(rv==-1);
	rv = OccYpos( snA, 1, 1,3);
	assert(rv==-1);
	rv = OccYpos( snA, 1, 0, 1);
	assert(rv==1);
	printf("Testing:OccYneg\n");
	rv = OccYneg( NULL, 1, 1,1);
	assert(rv==-1);
	rv = OccYneg( snA, 1, 1,1);
	assert(rv==0);
	rv = OccYneg( snA, 1, 4,1);
	assert(rv==-1);
	rv = OccYneg( snA, 1, 0,1);
	assert(rv==-1);
	rv = OccYneg( snA, -1, 1,1);
	assert(rv==-1);
	rv = OccYneg( snA, 3, 1,1);
	assert(rv==-1);
	rv = OccYneg( snA, 1, 1,-1);
	assert(rv==-1);
	rv = OccYneg( snA, 1, 1,3);
	assert(rv==-1);
	rv = OccYneg( snA, 1, 2, 1);
	assert(rv==1);
	printf("Testing:OccZpos\n");
	rv = OccZpos( NULL, 1, 1,1);
	assert(rv==-1);
	rv = OccZpos( snA, 1, 1,1);
	assert(rv==0);
	rv = OccZpos( snA, 1, 4,1);
	assert(rv==-1);
	rv = OccZpos( snA, 1, -1,1);
	assert(rv==-1);
	rv = OccZpos( snA, -1, 1,1);
	assert(rv==-1);
	rv = OccZpos( snA, 3, 1,1);
	assert(rv==-1);
	rv = OccZpos( snA, 1, 1,-1);
	assert(rv==-1);
	rv = OccZpos( snA, 1, 1,2);
	assert(rv==-1);
	rv = OccZpos( snA, 1, 1, 0);
	assert(rv==1);
	printf("Testing:OccZneg\n");
	rv = OccZneg( NULL, 1, 1,1);
	assert(rv==-1);
	rv = OccZneg( snA, 1, 1,1);
	assert(rv==0);
	rv = OccZneg( snA, 1, 4,1);
	assert(rv==-1);
	rv = OccZneg( snA, 1, -1,1);
	assert(rv==-1);
	rv = OccZneg( snA, -1, 1,1);
	assert(rv==-1);
	rv = OccZneg( snA, 3, 1,1);
	assert(rv==-1);
	rv = OccZneg( snA, 1, 1,0);
	assert(rv==-1);
	rv = OccZneg( snA, 1, 1,3);
	assert(rv==-1);
	rv = OccZneg( snA, 1, 1, 2);
	assert(rv==1);
	printf("Testing:OccYposPeriodic\n");
	rv = OccYposPeriodic( NULL, 1, 1,1);
	assert(rv==-1);
	rv = OccYposPeriodic( snA, 1, 1,1);
	assert(rv==0);
	rv = OccYposPeriodic( snA, 1, 3,1);
	assert(rv==0);
	rv = OccYposPeriodic( snA, 1, 4,1);
	assert(rv==-1);
	rv = OccYposPeriodic( snA, 1, -1,1);
	assert(rv==-1);
	rv = OccYposPeriodic( snA, -1, 1,1);
	assert(rv==-1);
	rv = OccYposPeriodic( snA, 3, 1,1);
	assert(rv==-1);
	rv = OccYposPeriodic( snA, 1, 1,-1);
	assert(rv==-1);
	rv = OccYposPeriodic( snA, 1, 1,3);
	assert(rv==-1);
	rv = OccYposPeriodic( snA, 1, 0, 1);
	assert(rv==1);
	printf("Testing:OccYnegPeriodic\n");
	rv = OccYnegPeriodic( NULL, 1, 1,1);
	assert(rv==-1);
	rv = OccYnegPeriodic( snA, 1, 1,1);
	assert(rv==0);
	rv = OccYnegPeriodic( snA, 1, 0,1);
	assert(rv==0);
	rv = OccYnegPeriodic( snA, 1, 4,1);
	assert(rv==-1);
	rv = OccYnegPeriodic( snA, 1, -1,1);
	assert(rv==-1);
	rv = OccYnegPeriodic( snA, -1, 1,1);
	assert(rv==-1);
	rv = OccYnegPeriodic( snA, 3, 1,1);
	assert(rv==-1);
	rv = OccYnegPeriodic( snA, 1, 1,-1);
	assert(rv==-1);
	rv = OccYnegPeriodic( snA, 1, 1,3);
	assert(rv==-1);
	rv = OccYnegPeriodic( snA, 1, 2, 1);
	assert(rv==1);

	printf("Testion:OccAllNei\n");
	rv = OccAllNei( NULL, 1, 1, 1);
	assert(rv==-1);
	rv = OccAllNei( snA, 1, 1, 1);
	assert(rv==0);
	rv = OccAllNei( snA, 0, 1, 1);
	assert(rv==-1);
	rv = OccAllNei( snA, 1, 0, 1);
	assert(rv==-1);
	rv = OccAllNei( snA, 1, 1, 0);
	assert(rv==-1);
	rv = OccAllNei( snA, 2, 1, 1);
	assert(rv==-1);
	rv = OccAllNei( snA, 1, 3, 1);
	assert(rv==-1);
	rv = OccAllNei( snA, 1, 1, 2);
	assert(rv==-1);
	sn1 = getSN(snA,1,2,1);
	setDwelStat(sn1,3);
	sn1 = getSN(snA,1,3,1);
	setDwelStat(sn1,4);
	sn1 = getSN(snA,0,2,1);
	setDwelStat(sn1,6);
	sn1 = getSN(snA,2,2,1);
	setDwelStat(sn1,7);
	sn1 = getSN(snA,1,2,2);
	setDwelStat(sn1,8);
	sn1 = getSN(snA,1,2,0);
	setDwelStat(sn1,9);
	rv = OccAllNei( snA, 1, 2, 1);
	assert(rv==1);
	
	printf("Testing:OccAllNeiPeriodicY\n");
	rv = OccAllNeiPeriodicY( NULL, 1, 1, 1);
	assert(rv==-1);
	rv = OccAllNeiPeriodicY( snA, 1, 1, 1);
	assert(rv==0);
	rv = OccAllNeiPeriodicY( snA, 1, 0, 1);
	assert(rv==0);
	rv = OccAllNeiPeriodicY( snA, 1, 3, 1);
	assert(rv==0);
	rv = OccAllNeiPeriodicY( snA, 1, 2, 1);
	assert(rv==1);
	rv = OccAllNeiPeriodicY( snA, -1, 1, 1);
	assert(rv==-1);
	rv = OccAllNeiPeriodicY( snA, 3, 1, 1);
	assert(rv==-1);
	rv = OccAllNeiPeriodicY( snA, 1, 1, -1);
	assert(rv==-1);
	rv = OccAllNeiPeriodicY( snA, 1, 1, 3);
	assert(rv==-1);
	rv = OccAllNeiPeriodicY( snA, 1, -1, 1);
	assert(rv==-1);
	rv = OccAllNeiPeriodicY( snA, 1, 4, -1);
	assert(rv==-1);
	

	printf("Testing:printVisitFreq Printing Site Node Array to VisitFreq.xyz file\n");
	char fil1[] = "File1\0";
	rv = printVisitFreq(NULL,&fil1[0]);
	assert(rv==-1);
	rv = printVisitFreq(snA,&fil1[0]);
	assert(rv==0);
	printf("Testing:deleteSNarray Deleting Site node array\n");
	rv = deleteSNarray(NULL);
	assert(rv==-1);
	rv = deleteSNarray(snA);
	assert(rv==0);

	printf("Testing:printPoint\n");
	rv = printPoint(NULL);
	assert(rv==-1);
	Point pt10 = newPoint();
	rv = printPoint(pt10);
	assert(rv==0);

	printf("Testing: printVisitFreq\n");
	rv = printVisitFreq(NULL, &fil1[0]);
	assert(rv==-1);
	SNarray snA2 = newSNarray(5,5,5);
	rv = setEnergy(getSN(snA2,2,2,2),-33);
	assert(rv==0);
	printf("Everything printed should be 0 except for the energy of site 3,3,3\n");
	printf("Which should have an energy of -33\n");
	
	char fil2[] = "File2\0";
	rv = printVisitFreq(snA2, &fil2[0]);

	return 0;

}
